// <auto-generated />
using System;
using BrunoTragl.Inovation.Videolocadora.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrunoTragl.Inovation.Videolocadora.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VideolocadoraContext))]
    [Migration("20201026060810_nullDefaultValues")]
    partial class nullDefaultValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrunoTragl.Inovation.Videolocadora.Domain.Model.Aluguel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Devolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Devolveu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(null);

                    b.Property<int>("FilmeId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Multa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(null);

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FilmeId");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("aluguel");
                });

            modelBuilder.Entity("BrunoTragl.Inovation.Videolocadora.Domain.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("Telefone")
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("Id");

                    b.ToTable("cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(277),
                            Email = "cleiton.feitosa@contoso.xpto.com",
                            Nascimento = new DateTime(1959, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Cleiton Alves",
                            Sobrenome = "Feitosa",
                            Telefone = "(31) 7011-2009"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1322),
                            Email = "leandro.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1977, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Leandro Gomes",
                            Sobrenome = "Silva",
                            Telefone = "(83) 8897-6044"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1350),
                            Email = "aline.hashers@contoso.xpto.com",
                            Nascimento = new DateTime(1973, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Aline Freitas",
                            Sobrenome = "Hashers",
                            Telefone = "(87) 9909-7301"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1359),
                            Email = "ze.braido@contoso.xpto.com",
                            Nascimento = new DateTime(1976, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "José de Arruda",
                            Sobrenome = "Braido",
                            Telefone = "(28) 1721-4240"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1369),
                            Email = "armando.severo@contoso.xpto.com",
                            Nascimento = new DateTime(1967, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Armando",
                            Sobrenome = "Severó",
                            Telefone = "(46) 5653-6061"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1432),
                            Email = "igor.leitosa@contoso.xpto.com",
                            Nascimento = new DateTime(1996, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Igor",
                            Sobrenome = "Leitosa",
                            Telefone = "(97) 1417-4051"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1441),
                            Email = "gustavo.trato@contoso.xpto.com",
                            Nascimento = new DateTime(1973, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gustavo",
                            Sobrenome = "Trato",
                            Telefone = "(17) 5319-5715"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1449),
                            Email = "guilherme.arruda@contoso.xpto.com",
                            Nascimento = new DateTime(1963, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Guilherme",
                            Sobrenome = "Arruda",
                            Telefone = "(68) 9287-9090"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1457),
                            Email = "rosa.lumini@contoso.xpto.com",
                            Nascimento = new DateTime(1971, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rosa Alves",
                            Sobrenome = "Lumini",
                            Telefone = "(98) 1573-7028"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1465),
                            Email = "david.carvalho@contoso.xpto.com",
                            Nascimento = new DateTime(1982, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "David Oliveira",
                            Sobrenome = "Carvalho",
                            Telefone = "(13) 8155-2068"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1472),
                            Email = "karine.cortez@contoso.xpto.com",
                            Nascimento = new DateTime(1974, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Karine Maria Gonçalves",
                            Sobrenome = "Cortez",
                            Telefone = "(85) 9089-8244"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1480),
                            Email = "gustavo.santos@contoso.xpto.com",
                            Nascimento = new DateTime(1943, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gustavo Pereira",
                            Sobrenome = "Santos",
                            Telefone = "(73) 3887-6251"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1487),
                            Email = "leandro.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1946, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Leandro José Paulo",
                            Sobrenome = "Silva",
                            Telefone = "(29) 8434-3042"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1495),
                            Email = "maria.santos@contoso.xpto.com",
                            Nascimento = new DateTime(1989, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Nainam Silvino Araújo",
                            Sobrenome = "Santos",
                            Telefone = "(68) 9100-1369"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1502),
                            Email = "jullieny.oliveira@contoso.xpto.com",
                            Nascimento = new DateTime(1940, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jullieny Melo",
                            Sobrenome = "Oliveira",
                            Telefone = "(84) 3518-9426"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1510),
                            Email = "daniel.rocha@contoso.xpto.com",
                            Nascimento = new DateTime(1953, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Daniel dos Santos",
                            Sobrenome = "Rocha",
                            Telefone = "(52) 5829-3529"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1517),
                            Email = "itamar.souza@contoso.xpto.com",
                            Nascimento = new DateTime(1962, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Itamar de Carvalho",
                            Sobrenome = "Souza",
                            Telefone = "(76) 6303-4153"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1525),
                            Email = "alvaro.batista@contoso.xpto.com",
                            Nascimento = new DateTime(1989, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Álvaro Rogério",
                            Sobrenome = "Batista",
                            Telefone = "(97) 8925-6042"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1532),
                            Email = "rita.santos@contoso.xpto.com",
                            Nascimento = new DateTime(1947, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rita de Cássia dos",
                            Sobrenome = "Santos",
                            Telefone = "(90) 3125-9966"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1540),
                            Email = "alcione.germino@contoso.xpto.com",
                            Nascimento = new DateTime(1969, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Alcione Monteiro Lucas",
                            Sobrenome = "Germino",
                            Telefone = "(18) 8575-9626"
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1547),
                            Email = "fabiana.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1988, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fabiana Flávia",
                            Sobrenome = "Silva",
                            Telefone = "(22) 5380-8402"
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1554),
                            Email = "carolina.souza@contoso.xpto.com",
                            Nascimento = new DateTime(1999, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carolina Caraciolo de",
                            Sobrenome = "Souza",
                            Telefone = "(33) 8671-3599"
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1562),
                            Email = "jonas.chaves@contoso.xpto.com",
                            Nascimento = new DateTime(1956, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Jonas Augusto de Barros",
                            Sobrenome = "Chaves",
                            Telefone = "(34) 8580-1863"
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1569),
                            Email = "carlos.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1994, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carlos Andrade",
                            Sobrenome = "Silva",
                            Telefone = "(49) 7398-8291"
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1590),
                            Email = "rosa.lumini@contoso.xpto.com",
                            Nascimento = new DateTime(1979, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Luciana Dutra Cavalcanti",
                            Sobrenome = "Ricarte",
                            Telefone = "(64) 9882-6677"
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1598),
                            Email = "denys.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1999, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Denys Vytor de Queiroz da",
                            Sobrenome = "Silva",
                            Telefone = "(99) 9549-4253"
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1605),
                            Email = "maria.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1943, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Auxiliadora da",
                            Sobrenome = "Silva",
                            Telefone = "(39) 1024-3288"
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1613),
                            Email = "marcello.veloso@contoso.xpto.com",
                            Nascimento = new DateTime(1976, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Marcello Henryque da Silva Souza",
                            Sobrenome = "Veloso",
                            Telefone = "(99) 6578-2563"
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1656),
                            Email = "marli.felix@contoso.xpto.com",
                            Nascimento = new DateTime(1988, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Marli Rodrigues",
                            Sobrenome = "Félix",
                            Telefone = "(27) 3001-8317"
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1664),
                            Email = "milena.souza@contoso.xpto.com",
                            Nascimento = new DateTime(1994, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Milena Rolim",
                            Sobrenome = "Souza",
                            Telefone = "(52) 5490-2440"
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1671),
                            Email = "glaucia.pereira@contoso.xpto.com",
                            Nascimento = new DateTime(1974, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Glaucia Adriana Dantas",
                            Sobrenome = "Pereira",
                            Telefone = "(39) 3572-6277"
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1679),
                            Email = "joane.carvalho@contoso.xpto.com",
                            Nascimento = new DateTime(1976, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Joane Maria da Silva de",
                            Sobrenome = "Carvalho",
                            Telefone = "(86) 2960-2642"
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1687),
                            Email = "kenia.arruda@contoso.xpto.com",
                            Nascimento = new DateTime(1987, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Kênia Stephanie Nunes",
                            Sobrenome = "Arruda",
                            Telefone = "(82) 8692-8729"
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1694),
                            Email = "lorena.farias@contoso.xpto.com",
                            Nascimento = new DateTime(1951, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Lorena Alcântara",
                            Sobrenome = "Farias",
                            Telefone = "(17) 8450-7968"
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1703),
                            Email = "maria.oliveira@contoso.xpto.com",
                            Nascimento = new DateTime(1974, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Gisele da Silva",
                            Sobrenome = "Oliveira",
                            Telefone = "(89) 1869-6420"
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1710),
                            Email = "diogo.souza@contoso.xpto.com",
                            Nascimento = new DateTime(1991, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Diogo Fernandes de",
                            Sobrenome = "Souza",
                            Telefone = "(23) 7945-6808"
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1718),
                            Email = "elivelton.silva@contoso.xpto.com",
                            Nascimento = new DateTime(1977, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Elivelton Costa da",
                            Sobrenome = "Silva",
                            Telefone = "(11) 4611-4084"
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1725),
                            Email = "genildson.oliveira@contoso.xpto.com",
                            Nascimento = new DateTime(1943, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Genildson Alvez de",
                            Sobrenome = "Oliveira",
                            Telefone = "(89) 4812-7020"
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1734),
                            Email = "gerdon.mafra@contoso.xpto.com",
                            Nascimento = new DateTime(1988, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gerdon Adler Ribeiro",
                            Sobrenome = "Mafra",
                            Telefone = "(68) 3585-8574"
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(1741),
                            Email = "gilberto.oliveira@contoso.xpto.com",
                            Nascimento = new DateTime(1967, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Gilberto",
                            Sobrenome = "Oliveira",
                            Telefone = "(87) 7913-5555"
                        });
                });

            modelBuilder.Entity("BrunoTragl.Inovation.Videolocadora.Domain.Model.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("filme");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(4402),
                            Descricao = "Jovens se aventuram em festas do colegial. Muita diversão e bebedeiras!!! HAHAHAHA",
                            Titulo = "American Pie 3",
                            UrlImagem = "https://vignette.wikia.nocookie.net/doblaje/images/1/1f/AmericanPieCampamento.jpg/revision/latest/top-crop/width/360/height/450?cb=20091001181345&path-prefix=es",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5363),
                            Descricao = "O ex-policial Brian comete uma grande traição, juntando-se a um amigo ex-presidiário no transporte de dinheiro sujo para uma importadora-exportadora muito suspeita.",
                            Titulo = "+ Velozes + Furiosos",
                            UrlImagem = "https://vignette.wikia.nocookie.net/velozes-e-furiosos/images/a/aa/Velozes_e_Furiosos_-_Capa.jpg/revision/latest/top-crop/width/360/height/450?cb=20180305235641&path-prefix=pt-br",
                            Valor = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5382),
                            Descricao = "A bordo do luxuoso transatlântico, Rose (Kate Winslet), uma jovem da alta sociedade, se sente pressionada com a vida que leva. Ao conhecer Jack (Leonardo DiCaprio), um artista pobre e aventureiro, os dois se apaixonam. Mas eles terão que enfrentar um desafio ainda maior que o preconceito social com o destino trágico do navio.",
                            Titulo = "Titanic",
                            UrlImagem = "https://vignette.wikia.nocookie.net/maritime-disaster/images/b/b3/300px-RMS_Titanic_3.jpg/revision/latest/top-crop/width/360/height/450?cb=20170425130744",
                            Valor = 6.50m
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5384),
                            Descricao = "Don Corleone (Marlon Brando) é chefe de uma das famílias de mafiosos italianos mais respeitadas de Nova York. Quando ele é ferido e afastado de suas funções, o filho Michael (Al Pacino) deve tomar as rédeas da situação para acabar com o responsável e manter a honra do pai intacta. Dirigido por Francis Ford Coppola e vencedor de três Oscars, incluindo o de Melhor Filme.",
                            Titulo = "O Poderoso Chefão",
                            UrlImagem = "https://images-na.ssl-images-amazon.com/images/I/41NrywwjCEL._AC_SY450_.jpg",
                            Valor = 7.80m
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5386),
                            Descricao = "Num futuro dominado pelas máquinas, os computadores mandam ao passado um androide (Arnold Schwarzenegger) praticamente indestrutível. Sua missão é matar Sarah Connor antes que ela dê à luz o líder da resistência humana na guerra contra a inteligência artificial. Os seres humanos também enviam um agente para proteger a mulher.",
                            Titulo = "O Exterminador Do Futuro",
                            UrlImagem = "https://vignette.wikia.nocookie.net/exterminadordofuturo/images/6/6f/Terminator.jpeg/revision/latest/top-crop/width/360/height/450?cb=20150730214551&path-prefix=pt-br",
                            Valor = 10.50m
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5388),
                            Descricao = "De volta para o terceiro ano em Hogwarts, Harry Potter (Daniel Radcliffe) encontra a escola sob estado de atenção: os sombrios dementadores cercam as proximidades do castelo em busca de Sirius Black (Gary Oldman), assassino recém-fugido da prisão de Azkaban que está atrás de Harry. Dirigido por Alfonso Cuarón e indicado ao Oscar de Melhor Canção Original e Melhores Efeitos Visuais.",
                            Titulo = "Harry Potter E O Prisioneiro De Azkaban",
                            UrlImagem = "https://vignette.wikia.nocookie.net/vozesportuguesas/images/a/a5/HP3.jpg/revision/latest/top-crop/width/360/height/450?cb=20200928052358&path-prefix=pt",
                            Valor = 8.50m
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5390),
                            Descricao = "Marty McFly (Michael J. Fox) é um jovem que acidentalmente viaja em uma máquina do tempo construída pelo cientista Doc Brown (Christopher Lloyd). Agora, nos anos 1950, ele vê seus pais que ainda não se apaixonaram. E, para não colocar em risco sua própria existência, ele precisa agir como cupido dos pais. Vencedor do Oscar de Melhor Edição de Som.",
                            Titulo = "De Volta Para O Futuro",
                            UrlImagem = "https://images-na.ssl-images-amazon.com/images/I/916GbiXiQCL._SY450_.jpg",
                            Valor = 8.50m
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5392),
                            Descricao = "Com o auxílio da engenharia genética criada pelos doutores Alan (Sam Neill), Ellie (Laura Dern) e Ian, um milionário traz à vida dinossauros extintos há milhares de anos, criando um imenso parque em uma remota ilha. Porém, os gigantes pré-históricos começam a ameaçar a vida dos vistitantes. Vencedor de 3 Oscars, incluindo o de Melhores Efeitos Visuais.",
                            Titulo = "Jurassic Park - O Parque Dos Dinossauros",
                            UrlImagem = "https://i.pinimg.com/originals/12/45/97/124597895a3367703ce104584c6dfd19.jpg",
                            Valor = 9.99m
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5394),
                            Descricao = "Na Terra-Média, o hobbit Frodo (Elijah Woods) recebe de presente de seu tio o Um Anel, um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso ele terá um caminho árduo pela frente, mas para o cumprimento desta jornada aos poucos ele poderá contar com outros seres que formarão a Sociedade do Anel.",
                            Titulo = "O Senhor dos Anéis: A Sociedade do Anel",
                            UrlImagem = "https://vignette.wikia.nocookie.net/liberproeliis/images/9/9a/Aragorn_Wikia.jpg/revision/latest/top-crop/width/360/height/450?cb=20200616201039&path-prefix=pt-br",
                            Valor = 7.60m
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5396),
                            Descricao = "Baseado na biografia de Stephen Hawking (Eddie Redmayne), o filme mostra as importantes descobertas do aclamado astrofísico sobre o tempo. Além de retratar seu relacionamento com a esposa Jane e os desafios que vieram com a descoberta de uma doença degenerativa.",
                            Titulo = "A Teoria De Tudo",
                            UrlImagem = "https://vignette.wikia.nocookie.net/figure-skating-13/images/2/29/Theoryofeverything.jpg/revision/latest/top-crop/width/360/height/450?cb=20181229212809",
                            Valor = 10.50m
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5398),
                            Descricao = "Oito anos após a morte de Harvey Dent, a cidade de Gotham City está pacificada e não precisa mais do Batman. A situação faz com que Bruce Wayne (Christian Bale) se torne um homem recluso em sua mansão, convivendo apenas com o mordomo Alfred (Michael Caine). Um dia, em meio a uma festa realizada na Mansão Wayne, uma das garçonetes contratadas (Anne Hathaway) rouba um colar de grande valor sentimental. Curioso em descobrir quem é ela, Bruce retorna à caverna para usar os computadores que tanto lhe serviram. Aos poucos começa a perceber indícios do surgimento de uma nova ameaça a Gotham City, personificada no brutamontes Bane (Tom Hardy). É o suficiente para que volte a ser o Batman.",
                            Titulo = "Batman: O Cavaleiro das Trevas Ressurge",
                            UrlImagem = "https://vignette.wikia.nocookie.net/marvel_dc/images/0/05/The_Dark_Knight_Rises_poster.jpg/revision/latest/top-crop/width/360/height/450?cb=20120123215909",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5400),
                            Descricao = "Quando Páris (Orlando Bloom), o príncipe de Troia, se apaixona por Helena (Diane Kruger), rainha de Esparta, o rei Menelau (Brendan Gleeson) inicia uma guerra de anos entre os dois reinos. Para vencer, Esparta conta com Aquiles (Brad Pitt), um guerreiro lendário que comanda um exército próprio. Indicado ao Oscar de Melhor Figurino.",
                            Titulo = "Tróia",
                            UrlImagem = "https://i.pinimg.com/474x/2d/35/6a/2d356a67ffb38bbe93e2959fe45265c4.jpg",
                            Valor = 6.70m
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5403),
                            Descricao = "Elizabeth Shaw (Noomi Rapace) e Charlie Holloway (Logan Marshall-Green) fazem parte de uma equipe de cientistas que embarca em uma jornada espacial para descobrir a verdade sobre a origem da raça humana. A nave Prometheus também é composta pelo robô David (Michael Fassbender), a diretora Meredith Vickers (Charlize Theron), o capitão Janek (Idris Elba), entre outros. Quando eles chegam ao planeta de destino, eles encontram criaturas poderosas, violentas e revelações estarrecedoras.",
                            Titulo = "Prometheus",
                            UrlImagem = "https://vignette.wikia.nocookie.net/theflophouse/images/1/19/Prometheus-poster.jpg/revision/latest/top-crop/width/360/height/450?cb=20170430003032",
                            Valor = 9.99m
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5405),
                            Descricao = "Baseado na história real de uma família de turistas durante um Tsunami que atingiu o sudeste asiático. Após a destruição causada pela onda gigante, uma mãe (Naomi Watts) tenta sobreviver com seu filho adolescente e reencontrar seu marido (Ewan McGregor) e seus dois filhos pequenos no meio do caos na Tailândia. Indicado ao Oscar de Melhor Atriz.",
                            Titulo = "O Impossível",
                            UrlImagem = "https://vignette.wikia.nocookie.net/my-little-baby-boy-harry-styles-fanfiction/images/f/fd/The_Impossible.png/revision/latest/top-crop/width/360/height/450?cb=20180923001955",
                            Valor = 8.99m
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5407),
                            Descricao = "A caminho da Terra, a nave Nostromo recebe um pedido de socorro de um planeta próximo. Ao desembarcar no local, um dos tripulantes é vítima de uma criatura alienígena, dando início a uma série de ataques assassinos dentro da espaçonave. Dirigido por Ridley Scott, o filme ganhou dois Oscars, incluindo o de Melhores Efeitos Visuais.",
                            Titulo = "Alien, O Oitavo Passageiro",
                            UrlImagem = "https://pm1.narvii.com/6960/c67686f08b1b55962883d5575c56aaeb798662aar1-360-450v2_00.jpg",
                            Valor = 10.50m
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5409),
                            Descricao = "A inusitada história de Oskar Schindler (Liam Neeson), um sujeito oportunista, sedutor, 'armador', simpático, comerciante no mercado negro, mas, acima de tudo, um homem que se relacionava muito bem com o regime nazista, tanto que era membro do próprio Partido Nazista (o que não o impediu de ser preso algumas vezes, mas sempre o libertavam rapidamente, em razão dos seus contatos).",
                            Titulo = "A Lista de Schindler",
                            UrlImagem = "https://vignette.wikia.nocookie.net/figure-skating-13/images/1/1f/MV5BMzMwMTM4MDU2N15BMl5BanBnXkFtZTgwMzQ0MjMxMDE%40._V1_SX640_SY720_.jpg/revision/latest/top-crop/width/360/height/450?cb=20160121092516",
                            Valor = 9.99m
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5411),
                            Descricao = "Em 1946, Andy Dufresne (Tim Robbins), um jovem e bem sucedido banqueiro, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela. Ele é mandado para uma prisão que é o pesadelo de qualquer detento, a Penitenciária Estadual de Shawshank, no Maine.",
                            Titulo = "Um Sonho de Liberdade",
                            UrlImagem = "https://images-na.ssl-images-amazon.com/images/I/8189H-FijZL._AC_SY450_.jpg",
                            Valor = 8.99m
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5413),
                            Descricao = "Mufasa (voz de James Earl Jones), o Rei Leão, e a rainha Sarabi (voz de Madge Sinclair) apresentam ao reino o herdeiro do trono, Simba (voz de Matthew Broderick). O recém-nascido recebe a bênção do sábio babuíno Rafiki (voz de Robert Guillaume), mas ao crescer é envolvido nas artimanhas de seu tio Scar (voz de Jeremy Irons), o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.",
                            Titulo = "O Rei Leão",
                            UrlImagem = "https://vignette.wikia.nocookie.net/vozesportuguesas/images/2/2e/O_Rei_Le%C3%A3o.jpg/revision/latest/top-crop/width/360/height/450?cb=20200718121256&path-prefix=pt",
                            Valor = 10.50m
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5415),
                            Descricao = "1935, no corredor da morte de uma prisão sulista. Paul Edgecomb (Tom Hanks) é o chefe de guarda da prisão, que temJohn Coffey (Michael Clarke Duncan) como um de seus prisioneiros. Aos poucos, desenvolve-se entre eles uma relação incomum, baseada na descoberta de que o prisioneiro possui um dom mágico que é, ao mesmo tempo, misterioso e milagroso.",
                            Titulo = "À Espera de um Milagre",
                            UrlImagem = "https://images-na.ssl-images-amazon.com/images/I/71D6IdIFSxL._AC_SY450_.jpg",
                            Valor = 9.40m
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5417),
                            Descricao = "Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump (Tom Hanks), um rapaz com QI abaixo da média e boas intenções. Por obra do acaso, ele consegue participar de momentos cruciais, como a Guerra do Vietnã e Watergate, mas continua pensando no seu amor de infância, Jenny Curran.",
                            Titulo = "Forrest Gump - O Contador de Histórias",
                            UrlImagem = "https://vignette.wikia.nocookie.net/figure-skating-13/images/7/7f/Large_pEYI2QILJWMN1ZeEMgMM0jxBVhK.jpg/revision/latest/top-crop/width/360/height/450?cb=20170318095424",
                            Valor = 8.20m
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5419),
                            Descricao = "Durante a Segunda Guerra Mundial na Itália, o judeu Guido (Roberto Benigni) e seu filho Giosué são levados para um campo de concentração nazista. Afastado da mulher, ele tem que usar sua imaginação para fazer o menino acreditar que estão participando de uma grande brincadeira, com o intuito de protegê-lo do terror e da violência que os cercam.",
                            Titulo = "A Vida é Bela",
                            UrlImagem = "https://images-na.ssl-images-amazon.com/images/I/51hH4OZGnLL._AC_SY450_.jpg",
                            Valor = 7.99m
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5421),
                            Descricao = "Em Vingadores: Guerra Infinita, Thanos (Josh Brolin) enfim chega à Terra, disposto a reunir as Joias do Infinito. Para enfrentá-lo, os Vingadores precisam unir forças com os Guardiões da Galáxia, ao mesmo tempo em que lidam com desavenças entre alguns de seus integrantes.",
                            Titulo = "Vingadores: Guerra Infinita",
                            UrlImagem = "https://vignette.wikia.nocookie.net/marvelcinematicuniverse/images/a/a0/AIWTAB.jpg/revision/latest/top-crop/width/360/height/450?cb=20200326084651",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5423),
                            Descricao = "Em Vingadores: Ultimato, após Thanos eliminar metade das criaturas vivas em Vingadores: Guerra Infinita, os heróis precisam lidar com a dor da perda de amigos e seus entes queridos. Com Tony Stark (Robert Downey Jr.) vagando perdido no espaço sem água nem comida, o Capitão América/Steve Rogers (Chris Evans) e a Viúva Negra/Natasha Romanov (Scarlett Johansson) precisam liderar a resistência contra o titã louco.",
                            Titulo = "Vingadores: Ultimato",
                            UrlImagem = "https://vignette.wikia.nocookie.net/universocinematograficomarvel/images/b/b7/Images.jpg/revision/latest/top-crop/width/360/height/450?cb=20190505233213&path-prefix=pt",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5425),
                            Descricao = "As forças imperais comandadas por Darth Vader (David Prowse/James Earl Jones) lançam um ataque contra os membros da resistência, que são obrigados a fugir. Enquanto isso, Luke Skywalker (Mark Hamill) tenta encontrar o Mestre Yoda, que poderá ensiná-lo a dominar a 'Força' e torná-lo um cavaleiro Jedi. No entanto, Darth Vader planeja levá-lo para o Lado Negro da 'Força'.",
                            Titulo = "Star Wars - O Império Contra-ataca",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/a/a8/TheEmpireStrikesBack_SFI_cover.jpg/revision/latest/top-crop/width/360/height/450?cb=20200303223254",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5427),
                            Descricao = "Com o desaparecimento de Luke Skywalker, a galáxia se encontra vulnerável para Kylo Ren e a Primeira Ordem. Rey, uma catadora de sucata do deserto, e Finn, um stormtrooper desertor, decidem se unir a Han Solo e Chewbacca numa busca desenfreada para restaurar a paz na galáxia.",
                            Titulo = "Star Wars: O Despertar da Força",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/b/b8/TFANewAdventures-Hardcover.jpg/revision/latest/top-crop/width/360/height/450?cb=20170519154150",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5429),
                            Descricao = "A jovem Rey começa a mostrar fortes sinais da Força, o que a faz procurar Luke Skywalker, que se vê obrigado a tomar uma decisão que mudará sua vida para sempre. Enquanto isso, a Primeira Ordem é liderada por Kylo Ren e o General Hux para um ataque contra Leia e a Resistência.",
                            Titulo = "Star Wars: Os Últimos Jedi",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/2/21/The_Last_Jedi_Studio_Fun.jpg/revision/latest/top-crop/width/360/height/450?cb=20201007114741",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5431),
                            Descricao = "Um grupo de heróis improváveis chamado Aliança Rebelde se une para realizar um movimento arriscado e rouba os planos da Estrela da Morte, arma responsável por destruir o Império.",
                            Titulo = "Rogue One: Uma História Star Wars",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/d/dc/RogueOneJuniorNovel-Hardcover.png/revision/latest/top-crop/width/360/height/450?cb=20161208092628",
                            Valor = 10.90m
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5434),
                            Descricao = "Com o retorno do Imperador Palpatine, todos voltam a temer seu poder. A Resistência toma a frente da batalha, enquanto Rey, treinando para ser uma Jedi, ainda se encontra em conflito com seu passado e futuro.",
                            Titulo = "Star Wars: A Ascensão Skywalker",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/c/cf/TROS-ExpandedEdition-Hardcover.jpg/revision/latest/top-crop/width/360/height/450?cb=20200413192610",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5436),
                            Descricao = "Em dificuldade financeira, o piloto Han Solo (Alden Ehrenreich) e sua namorada Qi'ra (Emilia Clarke) buscam algum trabalho. Eles conseguem pôr as mãos em uma substância valiosa, mas perigosa, que acaba levando à perseguição do Império e à separação entre os dois. Preocupado, Han usa toda a sua esperteza para se infiltrar num plano arriscado, mas que pode render a oportunidade de voltar à terra natal e reencontrar a sua amada. Caso ele falhe, vai ter que prestar contas ao perigoso Dryden Vos (Paul Bettany). No caminho, o piloto encontra parceiros importantes, como Chewbacca (Joonas Suotamo) e Lando Calrissian (Donald Glover), o proprietário original da Millennium Falcon.",
                            Titulo = "Han Solo: Uma História Star Wars",
                            UrlImagem = "https://vignette.wikia.nocookie.net/starwars/images/a/a9/Solo_A_Star_Wars_Story_Theatrical_Poster.png/revision/latest/top-crop/width/360/height/450?cb=20180409011120",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5438),
                            Descricao = "Ao desembarcar na Normandia, no dia 6 de junho de 1944, capitão Miller (Tom Hanks) recebe a missão de comandar um grupo do segundo batalhão para o resgate do soldado James Ryan, caçula de quatro irmãos, dentre os quais três morreram em combate. Por ordens do chefe George C. Marshall, eles precisam procurar o soldado e garantir o seu retorno, com vida, para casa.",
                            Titulo = "O Resgate do Soldado Ryan",
                            UrlImagem = "https://andersonvision.com/wp-content/uploads/2018/03/SPR_4K_3D-e1520299793289.jpg",
                            Valor = 7.99m
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5440),
                            Descricao = "Django (Jamie Foxx) é um escravo liberto cujo passado brutal com seus antigos proprietários leva-o ao encontro do caçador de recompensas alemão Dr. King Schultz (Christoph Waltz). Schultz está em busca dos irmãos assassinos Brittle, e somente Django pode levá-lo a eles. O pouco ortodoxo Schultz compra Django com a promessa de libertá-lo quando tiver capturado os irmãos Brittle, vivos ou mortos.",
                            Titulo = "Django Livre",
                            UrlImagem = "https://vignette.wikia.nocookie.net/sony-pictures-entertaiment/images/0/0b/P9287010_v_v8_aa.jpg/revision/latest/top-crop/width/360/height/450?cb=20190124223003",
                            Valor = 10.90m
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5442),
                            Descricao = "Cinco anos após convencer os habitantes de seu vilarejo que os dragões não devem ser combatidos, Soluço (voz de Jay Baruchel) convive com seu dragão Fúria da Noite, e estes animais integraram pacificamente a rotina dos moradores da ilha de Berk. Entre viagens pelos céus e corridas de dragões, Soluço descobre uma caverna secreta, onde centenas de novos dragões vivem. O local é protegido por Valka (voz de Cate Blanchett), mãe de Soluço, que foi afastada do filho quando ele ainda era um bebê. Juntos, eles precisarão proteger o mundo que conhecem do perigoso Drago Bludvist (Djimon Hounson), que deseja controlar todos os dragões existentes.",
                            Titulo = "Como Treinar o seu Dragão 2",
                            UrlImagem = "https://vignette.wikia.nocookie.net/universalstudios/images/3/36/How_to_train_your_dragon_2_poster.jpg/revision/latest/top-crop/width/360/height/450?cb=20200705012036",
                            Valor = 7.99m
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5444),
                            Descricao = "Nos dias finais do reinado de Marcus Aurelius (Richard Harris), o imperador desperta a ira de seu filho Commodus (Joaquin Phoenix) ao tornar pública sua predileção em deixar o trono para Maximus (Russell Crowe), o comandante do exército romano. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus, que consegue fugir antes de ser pego e passa a se esconder sob a identidade de um escravo e gladiador do Império Romano.",
                            Titulo = "Gladiador",
                            UrlImagem = "https://vignette.wikia.nocookie.net/samplelist/images/f/fb/Gladiator_%282000_film_poster%29.png/revision/latest/top-crop/width/360/height/450?cb=20200825182720",
                            Valor = 9.90m
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5446),
                            Descricao = "Em À Procura da Felicidade, Chris Gardner (Will Smith) é um pai de família que enfrenta sérios problemas financeiros. Apesar de todas as tentativas em manter a família unida, Linda (Thandie Newton), sua esposa, decide partir. Chris agora é pai solteiro e precisa cuidar de Christopher (Jaden Smith), seu filho de apenas 5 anos. Ele tenta usar sua habilidade como vendedor para conseguir um emprego melhor, que lhe dê um salário mais digno. Chris consegue uma vaga de estagiário numa importante corretora de ações, mas não recebe salário pelos serviços prestados.",
                            Titulo = "À Procura da Felicidade",
                            UrlImagem = "https://vignette.wikia.nocookie.net/jadensmith/images/8/81/Onesheet.jpg/revision/latest/top-crop/width/360/height/450?cb=20171128103224",
                            Valor = 10.00m
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5448),
                            Descricao = "Riley é uma garota divertida de 11 anos de idade, que deve enfrentar mudanças importantes em sua vida quando seus pais decidem deixar a sua cidade natal, no estado de Minnesota, para viver em San Francisco. Dentro do cérebro de Riley, convivem várias emoções diferentes, como a Alegria, o Medo, a Raiva, o Nojinho e a Tristeza. A líder deles é Alegria, que se esforça bastante para fazer com que a vida de Riley seja sempre feliz.",
                            Titulo = "Divertida Mente",
                            UrlImagem = "https://vignette.wikia.nocookie.net/vozesportuguesas/images/6/60/Divertida-Mente_%28Inside_Out%29.jpg/revision/latest/top-crop/width/360/height/450?cb=20200819022357&path-prefix=pt",
                            Valor = 7.99m
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5472),
                            Descricao = "Durante a Segunda Guerra Mundial, o médico do exército Desmond T. Doss (Andrew Garfield) se recusa a pegar em uma arma e matar pessoas, porém, durante a Batalha de Okinawa ele trabalha na ala médica e salva mais de 75 homens, sendo condecorado. O que faz de Doss o primeiro Opositor Consciente da história norte-americana a receber a Medalha de Honra do Congresso.",
                            Titulo = "Até o Último Homem",
                            UrlImagem = "https://vignette.wikia.nocookie.net/doblaje/images/b/b5/Hasta_el_ultimo_hombre_poster_oficial.jpg/revision/latest/top-crop/width/360/height/450?cb=20161214050010&path-prefix=es",
                            Valor = 10m
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5475),
                            Descricao = "Inglaterra, 1797. As cinco irmãs Bennet - Elizabeth (Keira Knightley), Jane (Rosamund Pike), Lydia (Jena Malone), Mary (Talulah Riley) e Kitty (Carey Mulligan) - foram criadas por uma mãe (Brenda Blethyn) que tinha fixação em lhes encontrar maridos que garantissem seu futuro. Porém Elizabeth deseja ter uma vida mais ampla do que apenas se dedicar ao marido, sendo apoiada pelo pai (Donald Sutherland). Quando o sr. Bingley (Simon Woods), um solteiro rico, passa a morar em uma mansão vizinha, as irmãs logo ficam agitadas. Jane logo parece que conquistará o coração do novo vizinho, enquanto que Elizabeth conhece o bonito e esnobe sr. Darcy (Matthew Macfadyen). Os encontros entre Elizabeth e Darcy passam a ser cada vez mais constantes, apesar deles sempre discutirem.",
                            Titulo = "Orgulho e Preconceito",
                            UrlImagem = "https://i.pinimg.com/474x/ca/7a/cf/ca7acf060eb528325ee8f5da4040d9d6.jpg",
                            Valor = 9.99m
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5477),
                            Descricao = "Jack (Edward Norton) é um executivo jovem, trabalha como investigador de seguros, mora confortavelmente, mas ele está ficando cada vez mais insatisfeito com sua vida medíocre. Para piorar ele está enfrentando uma terrível crise de insônia, até que encontra uma cura inusitada para o sua falta de sono ao frequentar grupos de auto-ajuda. Nesses encontros ele passa a conviver com pessoas problemáticas como a viciada Marla Singer (Helena Bonham Carter) e a conhecer estranhos como Tyler Durden (Brad Pitt). Misterioso e cheio de ideias, Tyler apresenta para Jack um grupo secreto que se encontra para extravasar suas angústias e tensões através de violentos combates corporais.",
                            Titulo = "Clube da Luta",
                            UrlImagem = "https://i.pinimg.com/originals/9e/a9/9e/9ea99e70bc6639670d1a506a18e83e22.jpg",
                            Valor = 9.99m
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5479),
                            Descricao = "Após ver a Terra consumindo boa parte de suas reservas naturais, um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper (Matthew McConaughey) é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand (Anne Hathaway), Jenkins (Marlon Sanders) e Doyle (Wes Bentley), ele seguirá em busca de uma nova casa. Com o passar dos anos, sua filha Murph (Mackenzie Foy e Jessica Chastain) investirá numa própria jornada para também tentar salvar a população do planeta.",
                            Titulo = "Interestelar",
                            UrlImagem = "https://vignette.wikia.nocookie.net/chrisnolan/images/4/46/Interstellar_poster.jpg/revision/latest/top-crop/width/360/height/450?cb=20160812013355",
                            Valor = 12.90m
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 938, DateTimeKind.Local).AddTicks(5481),
                            Descricao = "Em um futuro próximo, Thomas Anderson (Keanu Reeves), um jovem programador de computador que mora em um cubículo escuro, é atormentado por estranhos pesadelos nos quais encontra-se conectado por cabos e contra sua vontade, em um imenso sistema de computadores do futuro. Em todas essas ocasiões, acorda gritando no exato momento em que os eletrodos estão para penetrar em seu cérebro. À medida que o sonho se repete, Anderson começa a ter dúvidas sobre a realidade. Por meio do encontro com os misteriosos Morpheus (Laurence Fishburne) e Trinity (Carrie-Anne Moss), Thomas descobre que é, assim como outras pessoas, vítima do Matrix, um sistema inteligente e artificial que manipula a mente das pessoas, criando a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia. Morpheus, entretanto, está convencido de que Thomas é Neo, o aguardado messias capaz de enfrentar o Matrix e conduzir as pessoas de volta à realidade e à liberdade.",
                            Titulo = "Matrix",
                            UrlImagem = "https://imgc.artprintimages.com/img/print/carrie-anne-moss_u-l-pnenjz0.jpg",
                            Valor = 12.90m
                        });
                });

            modelBuilder.Entity("BrunoTragl.Inovation.Videolocadora.Domain.Model.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("Id");

                    b.ToTable("funcionario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 936, DateTimeKind.Local).AddTicks(1368),
                            Email = "adm@videolocadora.com.br",
                            Login = "admin",
                            Nome = "Administrador",
                            Senha = "123456",
                            Sobrenome = " "
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Cadastro = new DateTime(2020, 10, 26, 3, 8, 9, 937, DateTimeKind.Local).AddTicks(2899),
                            Email = "bruno.tragl@videolocadora.com.br",
                            Login = "brunotragl",
                            Nome = "Bruno",
                            Senha = "123456",
                            Sobrenome = "Tragl"
                        });
                });

            modelBuilder.Entity("BrunoTragl.Inovation.Videolocadora.Domain.Model.Aluguel", b =>
                {
                    b.HasOne("BrunoTragl.Inovation.Videolocadora.Domain.Model.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrunoTragl.Inovation.Videolocadora.Domain.Model.Filme", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BrunoTragl.Inovation.Videolocadora.Domain.Model.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
